get:
  summary: Get user settings
  tags:
    - Profile
  securitySchemes:
    - accessTokenCookie: []
  responses:
    "200":
      description: Current user settings
      content:
        application/json:
          schema:
            allOf:
              - $ref: ../../responses/Response.yaml
              - type: object
                properties:
                  data:
                    type: object
                    properties:
                      settings:
                        type: object
                        additionalProperties:
                          oneOf:
                            - type: string
                              nullable: true
                            - type: number
                              nullable: true
                            - type: boolean
                              nullable: true
                            - type: object
                              nullable: true
    "401":
      $ref: ../../responses/errors/UnauthorizedResponse.yaml
patch:
  summary: Update user settings
  tags:
    - Profile
  securitySchemes:
    - accessTokenCookie: []
  requestBody:
    content:
      application/json:
        schema:
          type: object
          additionalProperties:
            - type: string
              nullable: true
            - type: number
              nullable: true
            - type: boolean
              nullable: true
            - type: object
              nullable: true
  responses:
    "200":
      description: Current user settings
      content:
        application/json:
          schema:
            allOf:
              - $ref: ../../responses/Response.yaml
              - type: object
                properties:
                  data:
                    type: object
                    properties:
                      settings:
                        type: object
                        additionalProperties:
                          oneOf:
                            - type: string
                              nullable: true
                            - type: number
                              nullable: true
                            - type: boolean
                              nullable: true
                            - type: object
                              nullable: true
    "401":
      $ref: ../../responses/errors/UnauthorizedResponse.yaml
    "422":
      $ref: ../../responses/errors/ValidationErrorsResponse.yaml
