openapi: 3.0.3
info:
  version: 0.0.1
  title: KOK API
servers:
  - url: https://api.kok.dev-page.site
    description: Dev server
paths:
  /settings:
    $ref: ./routes/settings/SettingsList.yaml
  /settings/update:
    $ref: ./routes/settings/UpdateSettingViaUrl.yaml
  /auth/nonce:
    $ref: ./routes/auth/GetNonce.yaml
  /auth/login:
    $ref: ./routes/auth/Login.yaml
  /auth/refresh:
    $ref: ./routes/auth/RefreshAccessToken.yaml
  /auth/logout:
    $ref: ./routes/auth/Logout.yaml
  /me:
    $ref: ./routes/profile/CurrentUser.yaml
  /videos/random:
    $ref: ./routes/videos/GetRandomVideos.yaml
  /videos/{id}:
    $ref: ./routes/videos/Video.yaml
components:
  securitySchemes:
    accessTokenCookie:
      type: apiKey
      in: cookie
      name: access_token
    refreshTokenCookie:
      type: apiKey
      in: cookie
      name: refresh_token
tags:
  - name: Settings
    description: Global settings
  - name: Auth
    description: Auth endpoints
  - name: Profile
    description: Current user profile
  - name: Videos
    description: Videos endpoints
