openapi: 3.0.3
info:
  version: 0.0.1
  title: KOK API
paths:
  /settings:
    $ref: ./routes/settings/SettingsList.yaml
  /settings/update:
    $ref: ./routes/settings/UpdateSettingViaUrl.yaml
tags:
  - name: Settings
    description: Global settings
