openapi: 3.0.3
info:
  version: 0.0.1
  title: KOK API
servers:
  - url: https://api.kok.dev-page.site
    description: Main dev server
  - url: https://upload.kok.dev-page.site/
    description: Uploads server
paths:
  /common/leaderboard:
    $ref: ./routes/common/Leaderboard.yaml
  /settings:
    $ref: ./routes/settings/SettingsList.yaml
  /settings/update:
    $ref: ./routes/settings/UpdateSettingViaUrl.yaml
  /auth/nonce:
    $ref: ./routes/auth/GetNonce.yaml
  /auth/login:
    $ref: ./routes/auth/Login.yaml
  /auth/refresh:
    $ref: ./routes/auth/RefreshAccessToken.yaml
  /auth/logout:
    $ref: ./routes/auth/Logout.yaml
  /me:
    $ref: ./routes/profile/CurrentUser.yaml
  /me/settings:
    $ref: ./routes/profile/UserSettings.yaml
  /me/subscribers:
    $ref: ./routes/profile/Subs.yaml
  /me/subscriptions:
    $ref: ./routes/profile/Subs.yaml
  /me/playlists:
    $ref: ./routes/profile/PlaylistsList.yaml
  /me/playlists/{playlistId}:
    $ref: ./routes/profile/Playlist.yaml
  /me/playlists/{playlistId}/videos/:id:
    $ref: ./routes/profile/PlaylistVideo.yaml
  /me/favourites:
    $ref: ./routes/profile/FavouriteVideos.yaml
  /me/history:
    $ref: ./routes/profile/ViewsHistory.yaml
  /users/{address}:
    $ref: ./routes/users/User.yaml
  /users/{address}/videos:
    $ref: ./routes/users/UserVideos.yaml
  /users/{address}/subscriptions:
    $ref: ./routes/users/UserSubscriptions.yaml
  /users/{address}/playlists:
    $ref: ./routes/users/UserPlaylists.yaml
  /users/{address}/playlists/{playlistId}:
    $ref: ./routes/users/UserPlaylist.yaml
  /videos/random:
    $ref: ./routes/videos/GetRandomVideos.yaml
  /videos/trending:
    $ref: ./routes/videos/GetTrendingVideos.yaml
  /videos/{id}:
    $ref: ./routes/videos/Video.yaml
  /videos/{id}/likes:
    $ref: ./routes/videos/VideoLikes.yaml
  /videos/{id}/viewed:
    $ref: ./routes/videos/TrackVideoView.yaml
  /uploads:
    $ref: ./routes/uploads/Uploads.yaml
  /uploads/single:
    $ref: ./routes/uploads/UploadSingleFile.yaml
  /uploads/{id}:
    $ref: ./routes/uploads/UploadEntity.yaml
  /uploads/{id}/complete:
    $ref: ./routes/uploads/CompleteMultipartUpload.yaml
  /uploads/{id}/abort:
    $ref: ./routes/uploads/AbortMultipartUpload.yaml
components:
  securitySchemes:
    accessTokenCookie:
      type: apiKey
      in: cookie
      name: access_token
    refreshTokenCookie:
      type: apiKey
      in: cookie
      name: refresh_token
tags:
  - name: Common
    description: Common endpoints
  - name: Settings
    description: Global settings
  - name: Auth
    description: Auth endpoints
  - name: Profile
    description: Current user profile
  - name: Users
    description: Users (creators)
  - name: Videos
    description: Videos endpoints
  - name: Uploads
    description: Uploads endpoints (NOTE that you should switch to uploads server)
